# Simple workflow for deploying static content to GitHub Pages
name: Deploy Vue

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["vueElectron","vue"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies With -D Resolving @vitejs/plugin-vue Conflict
      run: npm i "@swc/wasm" glob -D
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Build
        run: npm run build
   #   - name: Auto Enable GitHub Pages
   #     id: pages
   #     uses: actions/github-script@v6
   #     with:
   #       script: |
   #         return (await github.rest.repos.createPagesSite({
   #           owner: context.repo.owner,
   #           repo: context.repo.repo,
   #         })).html_url;
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          enablement: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
